import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
led_pin_blue = 23
led_pin_green = 22
led_pin_red = 21

GPIO.setup(led_pin_blue, GPIO.OUT)
GPIO.setup(led_pin_green, GPIO.OUT)
GPIO.setup(led_pin_red, GPIO.OUT)

pwm_blue = GPIO.PWM(led_pin_blue,80)
pwm_green = GPIO.PWM(led_pin_green,80)
pwm_red = GPIO.PWM(led_pin_red,80)

pwm_blue.start(100)
time.sleep(1)
pwm_green.start(58)
time.sleep(1)
pwm_red.start(80)
time.sleep(3)
pwm_blue.start(38)
time.sleep(1)
pwm_green.start(10)
time.sleep(1)
pwm_red.start(21)
time.sleep(3)
pwm_blue.start(45)
time.sleep(1)
pwm_green.start(93)
time.sleep(1)
pwm_red.start(89)
time.sleep(3)
pwm_blue.start(73)
time.sleep(1)
pwm_green.start(7)
time.sleep(1)
pwm_red.start(3)
time.sleep(3)
pwm_blue.start(59)
time.sleep(1)
pwm_green.start(58)
time.sleep(1)
pwm_red.start(80)
time.sleep(3)
pwm_blue.start(38)
time.sleep(1)
pwm_green.start(87)
time.sleep(1)
pwm_red.start(45)
time.sleep(3)
pwm_blue.start(12)
time.sleep(1)
pwm_green.start(52)
time.sleep(1)
pwm_red.start(58)
time.sleep(3)
pwm_blue.start(79)
time.sleep(1)
pwm_green.start(13)
time.sleep(1)
pwm_red.start(3)
time.sleep(3)

pwm_blue.stop()
pwm_green.stop()
pwm_red.stop()

GPIO.cleanup()
